### ISSUE TITLE
Auto complete issues

### ISSUE THREAD

**Issue by azone** [withfig/fig#1031]
### Description:
1. Fig may fill a duplicate character in the terminal sometimes.
2. Fig may auto-submit the command when I press the `<Tab>` key sometimes, e.g. `git log<Tab>` may be equals `git log<Return>`
3. Fig will automatically change the path to the lowercased characters if auto-completes the path by the Fig. ![Mar-07-2022 14-15-08](https://user-images.githubusercontent.com/164407/156978362-19d3d21d-e6a4-4ac1-a72d-a4c1f3110159.gif)
4. FIg auto-fills a `<space>` after the long options.
![Mar-07-2022 14-35-49](https://user-images.githubusercontent.com/164407/156981009-d5395174-6302-4b72-a570-183fc8fbfe29.gif)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1|Version 1.0.55 (B383)|/opt/homebrew/bin/fish|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B383) [ABC – Extended]
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/loganwang/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path:
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path:
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: fish (773) - /dev/ttys001
Current working directory: /Users/loganwang/Documents/Projects/noah-ios/Worktree/feeding-analysis+revert-auto-premium-popup
Current window identifier: 44/% (com.googlecode.iterm2)
Path: /Users/loganwang/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin:/usr/local/opt/python@3.9/bin:/usr/local/opt/fzf/bin:/Users/loganwang/.fig/bin:/opt/homebrew/opt/fzf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/opt/homebrew/bin/:/Users/loganwang/.cargo/bin/:/Users/loganwang/Downloads/platform-tools/
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:469B3211-C3B4-454D-99B6-198899F024AC
  - FIG_TERM=1
  - FIG_CHECKED_PROMPTS=1
  - FIG_ENV_VAR=1
  - FIG_TERM_VERSION=4.0.10
  - FIG_INTEGRATION_VERSION=6
MacOS Version: 12.2.1 21D62
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,3
  - Chip: Apple M1 Pro
  - Cores: 8 (6 performance and 2 efficiency)
  - Memory: 16 GB</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
Hey @azone! Thanks for writing this up. Response is in sections since it was getting quite wordy.

---

> 1. Fig may fill a duplicate character in the terminal sometimes.

Not sure if we have an issue for this already...

Also @grant0417 - would the insertion lock changes fix this?

---

> 2. Fig may auto-submit the command when I press the <Tab> key sometimes, e.g. git log<Tab> may be equals git log<Return>

This happens when you get the red [>] icon. It's a feature called "instant execute". Relevant issue: #755

---

> 3. Fig will automatically change the path to the lowercased characters if auto-completes the path by the Fig.

Looks like you're using fish - I run into this too. What's happening is:
* A lower case letter has been typed
* Fish shows you an upper case letter since it found a case-insensitive match
* Fig matches case-insensitively
* When you hit enter to insert, fish stops showing the (fake) upper case letter

It could definitely insert the properly cased suggestion! Will create an issue for this.

---

> 4. Fig auto-fills a <space> after the long options.

Just opened a PR to fix this: https://github.com/withfig/autocomplete/pull/1015

Once it's merged, it should start working correctly 🙂

**Comment by azone** [comment]
Thanks, @SeparateRecords

**Comment by SeparateRecords** [comment]
Going to close this issue now since we've got other issues to follow up in. Thanks again for reporting this 🙂
