### ISSUE TITLE
VS Code extension: Improve extension's metadata

### ISSUE THREAD

**Issue by Tyriar** [withfig/fig#121]
The extension sticks out like a sore thumb :slightly_smiling_face: 

![](https://user-images.githubusercontent.com/2193314/120890360-119b2780-c5b7-11eb-9be3-613ebb9ef573.png)

I think it would also make sense to open source the VS Code extension as the source is already public and it's very simplistic. You could also consider [publishing it to the marketplace](https://code.visualstudio.com/api/working-with-extensions/publishing-extension) which would get auto updates working correctly and add another acquisition channel.

**Comment by mattschrage** [comment]
We should definitely open source the VSCode extension! 

Currently, we sideload the extension directly from the Fig macOS app, so we can ensure that the two stay in sync. Not clear to me that it makes sense to publish on the marketplace since, without the host macOS application, the extension wouldn't be very useful.
