### ISSUE TITLE
tmux with fig

### ISSUE THREAD

**Issue by JeffLabonte** [withfig/fig#1214]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
> Please include a detailed description of the feature (and an image or screen recording, if applicable)

I would like to be able to use fig with tmux. I do a lot of work in my terminal and I come from a Linux setup. So I am using tools that I used to use on Linux, such as tmux and alacrity. I know you guys are working on the implementation of alacritty, but it would be awesome if it would work with `tmux` as well.

I tried to use `tmux` in `iterm2` and it didn't work.

**Comment by grant0417** [comment]
Hey @JeffLabonte, are you using any plugins with `tmux` such as vim-tmux-navigator https://github.com/withfig/fig/issues/460

**Comment by JeffLabonte** [comment]
No, I am not. It really is basic tmux. Well with a few tweaks.

**Comment by grant0417** [comment]
Would you mind sharing your tmux config?

**Comment by Integralist** [comment]
👋🏻 @grant0417 

I'm also using tmux and have found fig _not_ to work.

Until recently it would work intermittently (at best) but since today's update I've found it just plain doesn't work at all inside tmux 😢 

I'm also using Alacritty so regardless of latest release: 'here be dragons' still 😬 

> **NOTE**: I've tested with the standard Terminal.app in macOS and fig appears to work within tmux there.

My config can be found here:
https://github.com/Integralist/dotfiles/blob/main/.tmux.conf

The use of tmux is essential for my development workflow and so tmux support here is greatly appreciated ❤️

**Comment by JeffLabonte** [comment]
Sorry for the delay, I didn't retry in the past weeks. I didn't have much time.

https://gist.github.com/JeffLabonte/f55f7373268aee374802b5eb4453bf56

**Comment by chaynabors** [comment]
@grant0417

**Comment by gv-sothebys-valdi** [comment]
I'm using fig with tmux in Kitty without problems :)

**Comment by JeffLabonte** [comment]
I will close this issue since it is also working for me on Alacritty with tmux! Thank you!
