### ISSUE TITLE
Conflict with starship prompt 

### ISSUE THREAD

**Issue by mschrage** [withfig/fig#125]
> The main issue I have is that sometimes the autocomplete doesn't kick in. I have to Ctrl-C or hit enter a few times to "reset" it.
>
> According to the debugger, I think [starship](https://starship.rs) might somehow be conflicting with fig but I'm not sure how to fix it.

**Comment by mattschrage** [comment]
Okay, I think I see what's going on. It seems like Fig is getting confused and sometimes thinks that the starship process is active instead of the shell (which prevents Fig's autocomplete from appearing). 

Next time you see `Debugger (starship)`, go to the submenu and click "Ignore".

<img width="731" alt="Screen Shot 2021-06-08 at 8 37 48 PM" src="https://user-images.githubusercontent.com/3155109/121289729-4b5f7d00-c89a-11eb-99a2-cf3dedf8a4b5.png">
