### ISSUE TITLE
Alacritty not supported 😢 

### ISSUE THREAD

**Issue by klauern** [withfig/fig#1312]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

My primary terminal is [Alacritty](https://alacritty.org/) and I noticed that Fig wasn't working on it.  I have no clue how much work this is to add, but it would be swell if it was added

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3.1|Version 1.0.56 (B421)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B421) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/nklauer/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @klauern! You're in luck because we literally just added support for this today on the beta distribution :)

Run `fig settings app.beta true` and then just open a new Alacritty session. You should be prompted to install the input method integration.

I'm going to close this for now, but please let me know if you run into any issues.
