### ISSUE TITLE
Autocomplete not working

### ISSUE THREAD

**Issue by reinhardtdjango** [withfig/fig#1448]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.1.0 (21C52)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B440) [Turkish Q]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/django/.fig/bin:/Users/django/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,2
  - Chip: 
  - Cores: 10
  - Memory: 32 GB
## OS Info:
  - macOS 12.1.0 (21C52)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/django
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 328/% (com.apple.Terminal)
  - Active Process: zsh (8606) - /dev/ttys005
  - Installed via Brew: true
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=A5E959E7-444B-4534-B47E-DA62FD2DF15F
    - PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/django/.fig/bin:/Users/django/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=8606
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by EmranMR** [comment]
Hi I have the same problem, Fig is no longer working on any of my terminals since this morning.
**Troubleshooting**
- Restarting Fig
- Restarting all my terminals
- Runing Fig doctor (everything came clear)
- Restarting the Mac itself
- Trying other terminals
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)



### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B440) [British]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Emran/.composer/vendor/bin:/Users/Emran/.fig/bin:/Users/Emran/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: iMac
  - Model Identifier: iMac19,1
  - Chip: 
  - Cores: 6
  - Memory: 52 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 126/% (com.panic.Nova)
  - Active Process: zsh (1371) - /dev/ttys002
  - Installed via Brew: true
  - Environment Variables:
    - PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Emran/.composer/vendor/bin:/Users/Emran/.fig/bin:/Users/Emran/.local/bin
    - TERM=xterm-256color
    - TERM_SESSION_ID=A8E04C70-1ED1-4403-AB0C-8874507B3DEB
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=1371
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by kritjo** [comment]
Same issue as of now, was working fine earlier today.
Fig suddenly not working at all (no autocomplete overlay). Problem in both iTerm and Terminal. `fig doctor` is happy, but menu-bar-icon is not:

![Screenshot 2022-05-12 at 12 39 09](https://user-images.githubusercontent.com/63654018/168054155-b8bedd5b-d960-4d85-9b03-d63b62a8f08d.png)


### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B440) [Norwegian]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/kritjo/.local/share/fig/plugins/git-open:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/kritjo/.fig/bin:/Users/kritjo/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,1
  - Chip: Apple M1 Pro
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/kritjo
  - CLI Installed: true
  - Executable Location: /opt/homebrew/bin/fig
  - Current Window ID: 3876/% (com.apple.Terminal)
  - Active Process: zsh (23664) - /dev/ttys004
  - Installed via Brew: true
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=7224E5A7-65D3-4D94-A877-2C3EEF33A268
    - PATH=/Users/kritjo/.local/share/fig/plugins/git-open:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/kritjo/.fig/bin:/Users/kritjo/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=23664
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: application is not present.
  - Docker: false

</p>
</details>

**Comment by reinhardtdjango** [comment]
exactly the same :(

**Comment by ayoush-wal** [comment]
exactly the same :(

**Comment by BruceMw** [comment]
Same issue since this morning. `fig doctor` say everything is working, but bar-icon says 'error loading the spec' and to check my internet

**Comment by reinhardtdjango** [comment]
not working on my end

**Comment by ajatkj** [comment]
Maybe try restarting fig/terminal.

![image](https://user-images.githubusercontent.com/8344288/168124977-643ee67c-3566-4756-bd86-d1f91b71850d.png)

**Comment by reinhardtdjango** [comment]
already tried that

**Comment by reinhardtdjango** [comment]
<img width="1728" alt="Screen Shot 2022-05-12 at 19 39 25" src="https://user-images.githubusercontent.com/98886087/168125690-8b6878db-ad3c-48a7-a48e-59eb7e20cb49.png">

**Comment by SeparateRecords** [comment]
Hey everyone! Sorry for the trouble - should be fine now. `fig restart` should definitely fix it now. If it doesn't let us know and we'll reopen the issue 🙂
