### ISSUE TITLE
Terminal emits - bind: No binding found for sequence 'fig-open-workflows'

### ISSUE THREAD

**Issue by jschank** [withfig/fig#1580]
### Description:
> after receiving latest update: 1.0.58 (B467), when I start up my terminal, it prints the message
bind: No binding found for sequence 'fig-open-workflows'

Before displaying the prompt

### Notes:
Fish is my login shell, even though the user is marked as bash
I use iTerm2
and starship.rs as my prompt

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.4.0|Version 1.0.58 (B467)|/usr/local/bin/fish|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.58 (B467) [U.S.] 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/jschank/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: true
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /Users/jschank/SYNC/scripts:/usr/local/sbin:/Users/jschank/.bin:/Users/jschank/Projects/Scripts/Ruby:/Users/jschank/Projects/Scripts/bash:/Users/jschank/Projects/Scripts/perl:/Users/jschank/Projects/Scripts/Geek Tool:/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/opt/gnu-tar/libexec/gnubin:/Users/jschank/.fastlane/bin:/Users/jschank/.local/bin:/Users/jschank/.cargo/bin:/Users/jschank/SYNC/Apps/go/bin:/usr/local/opt/go/libexec/bin:/Users/jschank/.nodenv/shims:/Users/jschank/.rbenv/shims:/Users/jschank/.rbenv/shims:/usr/local/opt/fzf/bin:/Users/jschank/.local/bin:/Users/jschank/.fig/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:~/.dotnet/tools:/usr/local/MacGPG2/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Library/TeX/texbin:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by hadnet** [comment]
Same here, always an error when updates. Fu**** annoying.

**Comment by mschrage** [comment]
@jschank thanks for letting us know. 

A fix should go live next week. In the meantime, updating to the beta should resolve this issue:
`fig settings app.beta true`

**Comment by jab** [comment]
Just hit this too and wanted to confirm that upgrading to the latest beta resolved the issue, nice. Thank you, @mschrage. Once this fix makes it into the next stable release, do you recommend going back to `app.beta = false` to avoid instability in the future? (How unstable do betas tend to be?) Thanks again, and thanks for the great work on Fig!

**Comment by jab** [comment]
Ooh, after spending another minute using the latest beta (1.0.58 (B468)), I already hit a new issue: Hitting Ctrl+F no longer accepts fish auto-completions, as it should, and instead causes Fig's "Create new Workflow..." UX to take over. Here's a screenshot where you can see I had typed "./u", then fish suggested the "./upgrade-dev-dependencies.sh" auto-completion, then I hit Ctrl+F to accept that completion, but instead of accepting it, Fig took over (but left that auto-completion visible):
<img width="354" alt="Screen Shot 2022-07-03 at 9 06 09 AM" src="https://user-images.githubusercontent.com/64992/177041117-21657b25-1093-445c-a41a-70a319923420.png">
I searched in Fig settings to see whether "Create new Workflow" has now been mapped to Ctrl+F, but couldn't find that.

Reporting this here for now to preserve the context, and check whether this is intended new behavior before reporting this as a new bug.

**Comment by jab** [comment]
Looks like the issue I reported in the previous comment made it into the latest stable release, so I opened a new bug to track it: #1620
