### ISSUE TITLE
bug: does not work in alpine / iSH

### ISSUE THREAD

**Issue by wardnath** [withfig/fig#1909]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Alpine / iSH

### Expected behaviour

Run 

```
curl -fSsL https://fig.io/install-headless.sh | bash
```

on iSH and it works

### Actual behaviour

![IMG_51792A5F9005-1](https://user-images.githubusercontent.com/4514195/196051799-b984edde-1d94-4a54-88d9-ddc579ec2263.jpeg)

Welcome to Alpine!
You can install packages with: apk add <package>
You may change this message by editing /etc/motd.
Nathan-Wards-iPhone:~# curl -fSsL https://fig.io/install-headless.sh | bash
10
Performing compatibility checks
Je [31mSystem not supported\e[Om
Nathan-Wards-iPhone:~# Nathan-Wards-iPhone:~#
Nathan-Wards-iPhone:~#

### Steps to reproduce

download iSH from app store

run 

```
curl -fSsL https://fig.io/install-headless.sh | bash
```

### Environment

```yaml
iSH https://github.com/ish-app/ish/

https://apps.apple.com/us/app/ish-shell/id1436902243

Current version: ish 1.2.3 build 298
alpine v3.14
```

**Comment by SeparateRecords** [comment]
Hey @wardnath! Unfortunately fig won't work in iSH because it requires a desktop environment. Will update the manual to clarify this.

Going to close this as out of scope for now. Not saying it won't be worked on in the future, but we don't have any plans for it right now 🙂

**Comment by wardnath** [comment]
desktop app for OS X is great - would love to see this run in other environments as well someday 👍

**Comment by SeparateRecords** [comment]
Definitely! The main challenge with getting it to work in a non-graphical environment is that Fig relies on a webview to draw its popup. Hypothetically possible for iSH, termux, blink.sh, etc. but impractically difficult because it requires bespoke integrations for each app and a _significant_ chunk of engineering time.

For great autocomplete in iSH, personally I'd suggest [zsh-autocomplete](https://github.com/marlonrichert/zsh-autocomplete). In a graphical environment I think fig is a better experience but for text-only this is pretty good. (Note that this incompatible with fig, so installing it on your Mac will prevent fig from showing suggestions)
