### ISSUE TITLE
Misleading Privacy Policy, poor user experience 

### ISSUE THREAD

**Issue by Vendicated** [withfig/fig#1937]
I was excited to try fig but very quickly turned away due to the poor privacy.

Your main page states
> The terminal is a sensitive environment. All cloud features are opt-in and your data is encrypted at rest. For autocomplete, all of your keystrokes are processed locally and never leave your device.

Yet when you read the detailed Privacy Policy (which most people will skip and blindly trust your main site's statement), you find out that every time you accept a suggestion it sends your current root command. And that root command was typed via keystrokes. So quite contrary to this summary, my keystrokes do leave my device. What if this root command is a confidential program?

That very same sentence also states that "all cloud features are opt-in", yet the very first thing you are prompted to do is enter your email. Why would you need my email, except for cloud features. There are several issues on this repo that complain about this, but all of them were closed with the reason that [this is by design to "provide support" and power cloud features](https://github.com/withfig/fig/issues/606#issuecomment-974456670). But weren't they supposed to be opt-in?

Even if you can look past these shady descriptions and try to opt out of telemetry you run into
```
$ fig settings telemetry.disabled true
error: credentials file does not exist
```
So you are required to login to opt out? This goes against the GDPR's suggestion to "make it easy for people to withdraw consent". Even Microsoft, who are known for their shady business practices, [let you opt out via an environment variable](https://learn.microsoft.com/en-us/dotnet/core/tools/telemetry#how-to-opt-out) and by the time I managed to opt out I already sent dozens of telemetry events and was forced to give you my email for a program that claims to work fully offline

Please
- Make a way to opt out locally before any telemetry is sent, either by making the fig command above work without login or via an environment variable. Or better yet, make telemetry opt-in or ask on first start of fig
- Fix the misleading description on the fig.io website

Thank you!

**Comment by SeparateRecords** [comment]
> [...] every time you accept a suggestion it sends your current root command. And that root command was typed via keystrokes. So quite contrary to this summary, my keystrokes do leave my device.

To be clear, it **doesn't** send the keystrokes: when you accept the `commit` suggestion from the git spec, it inherently _has_ knows what spec is being used in order to give you suggestions. It uses this spec name in the telemetry. This gives us metrics on what specs we should focus on, what should be loaded first, and what improvements would be the most valuable.

It doesn't send the name of the command being used as-typed. If it _is_ doing this, that is a bug and needs to be fixed.

---

> What if this root command is a confidential program?

Not possible, you can only "accept a suggestion" for commands that we have a spec for - all are in https://github.com/withfig/autocomplete.

---

> That very same sentence also states that "all cloud features are opt-in"

Clarifying this: the features are opt-in as in "you can choose to use them, they are not mandatory, you will not be forced to use them".

---

> Why would you need my email, except for cloud features

I get that we're sounding like a broken record but we're not doing anything shady here! It really is just so (a) it's easier to get in touch, and (b) you can use cloud features if you want to.

I think I commented it in the issue you linked to as well, but I'll say it again here too. We're not stopping you from using a burner email, redirect service, etc. You'll always be welcome to do that if you really hate cloud services or getting contacted by a human 😄

---

> Even if you can look past these shady descriptions and try to opt out of telemetry you run into
> ```
> $ fig settings telemetry.disabled true
> error: credentials file does not exist
> ```
> So you are required to login to opt out? 

This definitely needs to get fixed (cc @mschrage, ). Can understand how it comes off as scummy or sketchy, actually was just an oversight.

---

> * Make a way to opt out locally before any telemetry is sent, either by making the fig command above work without login or via an environment variable. Or better yet, make telemetry opt-in or ask on first start of fig
> * Fix the misleading description on the fig.io website

I agree with the first point! The second one, I don't think the description is misleading at all, but we'll take a look to see if we can word it more clearly or provide more info. Everyone reads things in different ways - something that's perfectly clear to one person may not be to another.

---

If I missed responding to something, it wasn't intentional. Let me know and I'll respond to it. Really appreciate your feedback, thank you for helping us.

**Comment by Vendicated** [comment]
Hi, thanks for taking the time to address my points!

> To be clear, it doesn't send the keystrokes: when you accept the commit suggestion from the git spec, it inherently has knows what spec is being used in order to give you suggestions 

My main issue with this is that the description on your site led me to believe that none of my input ever leaves my device, when that's not quite true as at least the root command does, in case fig autocompletes part of my command. I think it would be cool if this could communicated better, for example by changing it to `... all of your sensitive keystrokes...`

> > What if this root command is a confidential program?

> Not possible, you can only "accept a suggestion" for commands that we have a spec for - all are in https://github.com/withfig/autocomplete.

That's a very good point I didn't realise, thanks for clarifying that, this makes it a lot better 

> We're not stopping you from using a burner email, redirect service, etc.

But I don't think I should have to do this, that's pretty bad UX, we're dealing with a command line program here, not a website. If cloud features are supposed to be opt in then I would expect to only have to provide my email once I do actually want to use those features. I understand the wanting to communicate with your users part but if someone doesn't want this, they shouldn't have to resort to a burner email. Just a skip button would be awesome but I'm kind of beating a dead horse here!

**Comment by SeparateRecords** [comment]
> your site led me to believe that none of my input ever leaves my device, when that's not quite true

IIRC it's phrased as "none of your keystrokes ever leave your device" which isn't done to weasle-word our way out of anything. It's because it's true! We're not trying to hide anything, but the wording is what's leading to the miscommunication.

Your keystrokes *don't* ever leave your device, so re-stating it as suggested actually makes it less accurate. The solution here is to make sure people don't come away with the wrong impression. Will have a think on the wording and discuss with team.

There's lots of ways to solve this problem now that we know about it, thank you for pointing out the issue :)

**Lots** more thoughts on this but only so much time in a day 😅

> we're dealing with a command line program here, not a website

Ahh, I think we hit the root of the issue here! Looking at it with this context, I totally understand how this is the impression you came away with. This is our fault, we need to fix our messaging and we're in the process of evaluating this atm.

To us, Fig is a _suite of tools_, not just a command line program. IDE-like autocomplete, rethought shell configuration, one-click plugin installation, etc. If you don't want to use a particular tool, you don't have to! The core concept of the terminal itself is fantastic and doesn't need to be reinvented, but can definitely be modernized -- we're trying to bring the terminal to the 21st century!

With that context, I think it's more understandable?

> Just a skip button would be awesome but I'm kind of beating a dead horse here!

We've had internal discussions about this! There are tradeoffs of course. Nothing concrete planned yet. Just want to say it's not off the table.

Our target audience is terminal users. This is actually a _superset_ of **every developer** (turns out some students just... use vim for writing). This audience is obviously self-selecting for people that are more concerned about privacy than an average person. So this is something we'll have to consider carefully as we move forward.

**Comment by SeparateRecords** [comment]
Also just wanted to add, I appreciate that this has been so civil! Usually discussions about this kind of stuff become really negative very quickly, lots of people have incredibly strong opinions about it. Thank you for taking the time to really discuss with us 🙂

**Comment by grant0417** [comment]
Just want to follow up on the `fig settings` issue, this is not trying to enforce that you login first, actually the value is set but it is not set in out backend for syncing 
settings. You can verify this by looking at the `~/.fig/settings.json` file. This still definitely needs to be improved and it might be better as a dedicated command that can not fail i.e. `fig telemetry disable`

Also it is not listed anywhere but you can also set the `FIG_DISABLE_TELEMETRY` env var which will prevent telemetry events from being sent, however just be aware this will only affect processes where this is set so the desktop app will not be effected unless you set for the app's process before launch. 

We definitely do need to do better on communicating this, but hopefully these also alleviate some of the concerns.

**Comment by mschrage** [comment]
I'm going to close this issue, but there are two concrete fixes that we'll implement:

- [ ] Do not print error when updating telemetry preferences prior to logging in
- [ ] Improve messaging around exactly what metadata is tracked on insert ("The name of the CLI completion spec from our open-source repo")

**Comment by Vendicated** [comment]
That's great! Thanks for the swift response

**Comment by grant0417** [comment]
Just want to give a bit of an update on this, the next version of our beta will have a command `fig telemetry disable` which should work without being logged in and not spit out an error, will update our docs once it hits stable to be the recommended way to update telemetry setting.
