### ISSUE TITLE
[BUG] Fig uninstallation leaves trace: `zsh:1: command not found: fig`

### ISSUE THREAD

**Issue by ggrelet** [withfig/fig#32]
**Summary:**
After I uninstalled `Fig.app`, `zsh:1: command not found: fig` is prompted every time I launch `git push`

**Steps to Reproduce:**
1. Install `Fig.app`
2. Uninstall `Fig.app`
3. Commit something
4. Push the code

**Expected Results:**
No error or warning from fig is thrown

**Actual Results:**
```
$ git push
zsh:1: command not found: fig
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 4 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 349 bytes | 349.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
remote:
remote: View merge request for XXXXXXX:
remote:   XXXXXXXXX
remote:
To XXXXXXXXXXX
   c3133a2..8d4ee7f  XXXXXXXXXXX -> XXXXXXXXXXX
```

**System information:**
OS: MacOS Catalina 11.15.7
Terminal: iTerm2 3.4.3
Version of Fig: 2.0

**Additional information**
I cleaned my `$PATH` and `.zshrc` from anything related to fig.

**Comment by falky97** [comment]
If you uninstall Fig, it deletes Fig's macOS app and CLI tool. Fig has asynchronous hooks set up after you execute a command that use the Fig CLI. 

I believe what happened it you opened a new Terminal window which sourced the `~/.fig/fig.sh` script. Then you uninstalled Fig, but because that script had already been sourced, the Fig commands remained in your current terminal session. 

If you open a new terminal session, Fig should be gone, correct?


**Two fixes for this:** 
1. Make the error output of the Fig commands go to /dev/null
2. Set a popup on uninstall that tells you Fig will still be active in existing terminals

**Comment by ggrelet** [comment]
> If you open a new terminal session, Fig should be gone, correct?

Unfortunately that's not the case... I tried with several new terminal windows. I even reboot my laptop.

Moreover I see the exact same problem when using `ssh`:
```
localhost $ ssh me@XX.XX.XX.XX
Password:
zsh:1: command not found: fig
remoteconsole $ logout
Shared connection to XX.XX.XX.XX closed.
```

**Comment by falky97** [comment]
Ohhhh, I see problem. 

You will need to remove Fig's SSH integration from your `~/.ssh/config` file. We append the below to the top of your file:

```
# Fig SSH Integration: Enabled
Host *
    ControlPath ~/.ssh/%r@%h:%p
    ControlMaster auto
    ControlPersist 1
    PermitLocalCommand yes
    LocalCommand (fig bg:ssh ~/.ssh/%r@%h:%p &)
```

@mattschrage We need to remove our SSH stuff from the install script!


My apologies, I misread your original post. I thought `git push` was just an example. But this makes sense as under the hood, git push/pull can use SSH

**Comment by ggrelet** [comment]
That was it, thanks for your support!
