### ISSUE TITLE
Onboarding - Mention `.fig.dotfiles.bak` folder

### ISSUE THREAD

**Issue by claudiodekker** [withfig/fig#389]
Right now, when Fig is installed fresh, certain (dot)files are copied into a `.fig.dotfiles.bak` backup folder. According to @mschrage, the purpose of this feature/folder is to prevent rare edge cases where the installation accidentally messes them up.

For most people however, installation tends to go well, but we of course still end up with this folder with no mention of what it is for and whether it's safe to delete (it is). **Would it be a good idea to mention this folder at the end of the onboarding, so that users are aware of what it's for and that they can delete it if everything seems in order?**

Example of the mentioned folder:
![Screenshot_2021-08-25_at_22 35 20](https://user-images.githubusercontent.com/1752195/130861780-a934086c-9a60-49a8-bb6e-719f0237046f.png)

**Comment by mschrage** [comment]
@pranavpeshwe creating copies of dotfiles is fairly standard for tools that make changes. I think think we should keep this for the time being since there are always new edge cases that emerge.

As for the location, I can see arguments for both. Benefit of keeping it separate from `.fig` is that if the user uninstalls the app and deletes the .fig folder, the backup still exists.

**Comment by pranavpeshwe** [comment]
Sure. 
And what do you think of mentioning it to the users? I think @claudiodekker has a point that it would be good to share with users that their stuff is backed up in the dotfiles dir, so that they can decide what to do with the backups.

**Comment by mschrage** [comment]
Definitely make sense to add a line in the shell onboarding saying that a backup of the user's dotfiles has been made!

**Comment by mschrage** [comment]
@pranavpeshwe @claudiodekker This is included in the next release (v1.0.49)!
