### ISSUE TITLE
Fig uninstall script does not remove fig lines from all dotfiles

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#448]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:

User uninstalled Fig from fig menu -> integrations -> uninstall but the lines sourcing fig.sh and pre.sh were still in .zshrc.

### Environment

```bash
N/A
```

**Comment by bmironer** [comment]
also
- the top block is inserted before any shebang lines... should probably insert on the first non-comment line instead.
- the bottom block returns a non-zero status, causing the terminal to turn red on startup with starship.rs or other last-command-status vizualizers. better use a proper if-clause instead of the current [-s test] && source xx.
