### ISSUE TITLE
"valet start/stop" command adds additional line break when pressing enter

### ISSUE THREAD

**Issue by rom3k** [withfig/fig#501]
### Description:
When trying to write `valet start` and pressing enter line breaks which makes it look like command is executing.
<img width="440" alt="obraz" src="https://user-images.githubusercontent.com/32843188/136340761-b5c03e8c-e08f-4738-b321-f8132828c3bd.png">
<img width="330" alt="obraz" src="https://user-images.githubusercontent.com/32843188/136340802-74f54845-c46f-476d-bdcb-d154702e5dc9.png">

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.0|Version 1.0.50 (B274)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.50 (B274) [Polish - Pro] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/romek/.fig/bin/fig
Accessibility: true
Number of specs: 211
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/opt/mysql@5.7/bin:/Users/romek/.nvm/versions/node/v14.17.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/romek/.fig/bin:/Users/romek/.composer/vendor/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by fwesss** [comment]
@rom3k Does this only happen for this specific command?

**Comment by fwesss** [comment]
@rom3k I've looked at the completion spec for valet and there isn't anything in there that should be causing this. I also wasn't able to reproduce on my end.

We fixed a bug that was causing Fig to paste additional input into the terminal buffer yesterday and I'm wondering if that was the root cause of this bug. Can you try restarting Fig and see if you still run into this?

<img width="209" alt="Screen Shot 2021-10-14 at 9 26 21 AM" src="https://user-images.githubusercontent.com/10150898/137358408-8df6705b-ccc8-4c9a-a186-7118d7cd0353.png">
