### ISSUE TITLE
Tutorial --> no autocomplete

### ISSUE THREAD

**Issue by haakonstorm** [withfig/fig#54]
### Description:![Screen Recording 2021-04-20 at 23 50 21](https://user-images.githubusercontent.com/193781/115468883-02912d80-a234-11eb-94c4-25189b036d41.gif)> Please include a detailed description of the issue (and an image or screen recording, if applicable)
Followed installer
Got exited
Typed `cd ` ...
waaa no autocomplete?
I see the "iterm integration" (as seen below) isn't installed. But I thought the tutorial was supposed to start after the iTerm integration? Needs to be looked into.

### Details:
|macOS|Fig|Shell|
|----|----|----|
|11.2.3|Version 1.0.40 (B188)|/bin/zsh|

<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.40 (B188)
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/s/.fig/bin/fig
Accessibility: true
Number of specs: 77
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/s/.fig/user/keybindings
iTerm Integration: false
Hyper Integration: false
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: 4287/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by haakonstorm** [comment]
Yup, installer was a little fast starting the tutorial somehow.

<img width="393" alt="Screenshot of iTerm2 (20-04-2021, 23-57-04)" src="https://user-images.githubusercontent.com/193781/115468995-29e7fa80-a234-11eb-89d6-59c4e8ea4b97.png">

This is cool. I'm gonna look into this from all angles, guys, keep up the great work!

**Comment by falky97** [comment]
Thanks so much for reporting this... We've been having some weird issues with this. Fig is not designed to work in scripts (only interactive shell processes), but we had to write some hacks to get it to work!

We will try to investigate the solution to this. From speaking with you outside the github, it seems like you have quite a custom environment so that certainly doesn't help here!

For other users running into this issue, hitting ctrl+c to quit the onboarding, then running `fig onboarding` should make it work...

I think the temp fix is adding a line to the onboarding saying the above^

**Comment by mschrage** [comment]
This should be fixed now! Closing this issue now, but will reopen it if anyone else is experience it! :)
