### ISSUE TITLE
[Integration] Panic's Nova editor terminal.

### ISSUE THREAD

**Issue by mikebronner** [withfig/fig#67]
**Is your feature request related to a problem? Please describe.**
Currently not functional in Nova editor terminal.

**Describe the solution you'd like**
Would love to see FIG integrated to work in Nova's integrated terminal.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by mattschrage** [comment]
I will investigate!

**Comment by mattschrage** [comment]
It looks like getting the cursor location is quite easy since Panic built Nova using Cocoa (so there is built in accessibility support for free).

However, I couldn't find an API for listening for when the active terminal changes. Fig requires this in order to know which terminal session (and `tty`) you are currently using.

 I posted a [question](https://devforum.nova.app/t/api-for-recieving-a-notification-when-the-active-terminal-changes/858) on the Nova developer forum and will report back.

**Comment by mattschrage** [comment]
Seems like there is currently no API that enables this, but I've submitted a 'feature request'.

**Comment by mschrage** [comment]
This is coming in the next release. (They never added the API, but we no longer require it)

**Comment by AndrewMac** [comment]
This is great news … but I can't seem to get it to work. Is there any additional setup required?
