### ISSUE TITLE
Integrate Fig with Tmux

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#699]
Fig is already partly integrated with Tmux - this issue will be closed once the integration works consistently.

**Comment by brendanfalk** [comment]
Fig should now officially support tmux. If it doesn't, it is likely due to a special tmux plugin you have.

If you use vim-tmux-navigator: https://github.com/christoomey/vim-tmux-navigator/issues/295#issuecomment-1021591011 

If it's something else, please create an issue with your tmux.conf file and bashrc/zshrc and we will investigate
