### ISSUE TITLE
is_vim command doesn't work in tmux

### ISSUE THREAD

**Issue by brendanfalk** [withfig/fig#705]
Awaiting more info from user

**Comment by lourenci** [comment]
Sorry for the misleading title. 

I use this [snippet](https://github.com/christoomey/vim-tmux-navigator#add-a-snippet) to bind some conditional keys in tmux depending on what application I'm currently using. When I use fig, the command `ps -o state= -o comm= -t '#{pane_tty}'` does not return the app I'm currently using. Without fig, there is no such an issue with that command.

Tks.

**Comment by gwenwindflower** [comment]
i brought this up in the discord once, a few months ago, had the same issue -- same issue breaks this plugin https://github.com/christoomey/vim-tmux-navigator -- i stopped using Fig because of it. was actually, serendipitously, just checking in to see if it had been fixed yet after seeing the most recent product email, but it appears not 😭

**Comment by sullivan-sean** [comment]
Closing this issue in favor of https://github.com/withfig/fig/issues/705 which has a more descriptive title. Can continue the conversation there if people continue to have compatibility issues with `vim-tmux-navigator`
