### ISSUE TITLE
[Onboarding] Make user aware of edits to shell config / dotfiles 

### ISSUE THREAD

**Issue by brendanfalk** [withfig/fig#757]
We should make it super clear exactly what code is being added to the user's dotfiles upon installation of Fig.

Suggestion is we have a dropdown like we do with the privacy policy that allows users to see it if they want to poke around.

**Comment by SeparateRecords** [comment]
Adding to this: it would be great to allow people to deselect shells they don't want support for (so fig won't create the profile/rc), eg.

- [x] zsh
- [x] fish
- [ ] bash

I didn't even have a bashrc/bash_profile before installing fig since I just... never needed to use bash. Helps keep the home dir cleaner

**Comment by grant0417** [comment]
New onboarding makes this clearer
