### ISSUE TITLE
Make it easier to see generators logs

### ISSUE THREAD

**Issue by brendanfalk** [withfig/fig#790]
Currently, it's not particularly clear in our docs how to see the logs / output from generators used in an autocomplete spec. 

https://fig.io/docs/concepts/logging-guide

We should make this very very clear and easy and give examples!

**Comment by davidalpert** [comment]
when I was troubleshooting my initial `fig` install, the issue wound up being that:
- the generators were invoking shell commands to populate their suggestions
- in my environment those shell commands were loading my init scripts
- my init scripts had some bugs and were doing silly things like running `docker ps` commands (whether docker was running or not) and initializing my `ssh-agent` _in each new shell_ which kept prompting me to enter input (and waiting until I entered input)

so all I could see in the developer tools console window was that the shell commands were timing out, but the console window didn't have any output from those shell commands so I couldn't see what they were doing and why they were taking so much time as to time out.

I seem to have misplaced my notes on how I learned what the problem was but it was something like
```
fig debug logs pty unix c_pty
```
that finally showed me the STDOUT of those sub shells and I saw that they were asking a question and pausing for keyboard input (which never came in the subshell).

**Comment by mschrage** [comment]
@davidalpert this problem is especially acute for developers building completion specs. Currently it is challenging to see the output if you add a `console.log` while contributing.

I think the ideal behavior from a developer perspective would be for logging to appear directly in the terminal.

<img width="444" alt="Screen Shot 2022-01-19 at 10 14 19 AM" src="https://user-images.githubusercontent.com/3155109/150190024-fb4179d8-6b94-466b-9446-c409c41fbc27.png">

Any `console.log` statements in a generator would be written to a logfile. Then in [withfig/autocomplete-tools `dev` script](https://github.com/withfig/autocomplete-tools/blob/main/packages/autocomplete-tools/scripts/dev.ts), we can watch this file for changes.

What do you think @fedeci?

**Comment by fedeci** [comment]
It shouldn't be difficult to implement. I need to check a few things in the AE codebase before giving a feedback on implementation.

**Comment by fedeci** [comment]
Since specs are TS files that we dynamically import in the AE we can't pipe the output of the console to a file as we would do for files executed with ts-node. We should actually expose a `console.out` (non-existent method in JS) that allows to output to a file the message and then watch it or do whatever we want.
/cc @mschrage

**Comment by mschrage** [comment]
This makes sense to me. Also we can just replace `console.log` with a custom function before running the generator and then switch back after. https://stackoverflow.com/a/7042634

And we can add a Fig.js API for appending to a file.

**Comment by fedeci** [comment]
I thought at replacing `console.log` too and I was wondering if we really want all the autocomplete messages (not only in development but also in production) to be piped to a `file.log` and not to the browser console. 
The DX would definitely get benefits from replacing `console.log` and companion methods!

**Comment by fedeci** [comment]
We are already using `autocomplete.log` file, right?
https://user-images.githubusercontent.com/38510000/151428709-8b9c42c7-a9d9-45e6-8daf-f78523aa1779.mov

**Comment by mschrage** [comment]
@fedeci this looks amazing! It is suuuch a big improvement over the Web Inspector console, I think.

And yeah we already use `autocomplete.log`, we could go with `specs.log` instead. (Or this file could be saved somewhere other than `~/.fig/logs`)

> I thought at replacing `console.log` too and I was wondering if we really want all the autocomplete messages (not only in development but also in production) to be piped to a `file.log` and not to the browser console. 
The DX would definitely get benefits from replacing `console.log` and companion methods!

For completion spec developers, I think the behavior is that we only write to a file when in "dev mode" and just the console statements that occur in generators.

But you're totally right that this improves the DX when working on the autocomplete engine as well!

**Comment by fedeci** [comment]
I'll enable it for development only then replacing `console.log`, it may be useful in the future to keep an error.log of generators for prod.

**Comment by mschrage** [comment]
We can even get fancy and have `console.error` and `console.warn` write to different log files and get output as different colors. (Not necessary at all for the first iteration)

**Comment by SeparateRecords** [comment]
@fedeci this is implemented now, right? Or did we want to keep it open to track adding more features?

**Comment by fedeci** [comment]
Let's close this one! It is completed and I left a comment in the engine with the todo!
