### ISSUE TITLE
Email verification timeout

### ISSUE THREAD

**Issue by tonysorensen** [withfig/fig#878]
User is unable to get email verification code in time to respond.

Please subscribe to this issue to get an update when Fig's email verification timeout is fixed.

**Comment by brendanfalk** [comment]
When users login to fig, we send a verification code via email to verify their identity. The timeout for verifying the email is 60 seconds. In some cases, these emails are taking more than 60 seconds to be received meaning the user can't login in the first place.

We believe this could have something to do with user's using VPNs, using specific work emails, or even logging in from certain countries (e.g. in Asia)

**Suggested workarounds**
* Use a personal email instead of work
* Avoid using VPNs etc

**Comment by fedeci** [comment]
Couldn't we increase the timeout to two minutes and a half? Would that solve the issue?

**Comment by brendanfalk** [comment]
we are switching login providers and will do this then. I don't think we can change the timeout with current login providers unfortunately :/

**Comment by brendanfalk** [comment]
This will be fixed today!
