### ISSUE TITLE
SSH error when using `ssh -J host1 host2` when config is shared

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#941]
From emails:

> * It affects Linux servers where Fig is not installed. I do share my Bash profile files between my Macs and Linux servers: I like to maintain the single consistent profile.
> * One of my Macs have SSH configured for jump hosts: only one server can be remoted into directly, others have to be jumped to via the "direct" server. In the absence of Fig everything works fine.
> * When Fig is installed into Bash profiles (Mac and Linux) jumping hosts fails with an SSH error. I can still SSH into the "direct" server.

On a laptop without my main Mac so I don't have a remote to test this on yet.

**Comment by DKroot** [comment]
OK, here are additional details.

1. The issue is reproducible once I install the latest Fig (1.0.55) on Mac (`brew install fig`).  If I revert Fig's changes in Bash profile files on the Mac, the issue goes away. This seems to be not related to the Linux profiles.
2. I get `kex_exchange_identification: banner line contains invalid characters` error when trying to SSH using a jump host to `host2`.
3.`~/.ssh/config`:
```
# global defaults for all hosts
Host *
  # Sets a timeout interval in seconds after which if no data has been received from the server, ssh(1) will send a
  # message through the encrypted channel to request a response from the server. The default is 0 (no messages).
  ServerAliveInterval 120

  # Sets the number of server alive messages (see below) which may be sent without ssh(1) receiving any messages back from
  # the server. If this threshold is reached while server alive messages are being sent, ssh will disconnect from the
  # server, terminating the session.
  ServerAliveCountMax 30

  # Specifies the timeout (in seconds) used when connecting to the SSH server, instead of using the default system TCP
  # timeout. This value is used only when the target is down or really unreachable, not when it refuses the connection.
  ConnectTimeout 30

  # Use passphrase from the keychain
  UseKeychain yes
  AddKeysToAgent yes
  IdentityFile ~/.ssh/id_rsa

Host host2
  ProxyJump {user}@host1
```

I've attached Bash profile files to reproduce the problem:
[Bash_profile.zip](https://github.com/withfig/fig/files/8073892/Bash_profile.zip)

**Comment by mschrage** [comment]
I wonder if this is related to #937?

**Comment by DKroot** [comment]
I've upgraded to 1.0.57 and retested. It's fixed! Thanks!

**Comment by mschrage** [comment]
Great! Thanks for letting us know @DKroot.
